[2024-09-15 19:40:51,639] 97 werkzeug -INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-15 19:40:51,639] 97 werkzeug -INFO - [33mPress CTRL+C to quit[0m
[2024-09-15 19:40:57,934] 838 app -ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\ineroun classes\internship_project(Stores_sales_production)\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ineroun classes\internship_project(Stores_sales_production)\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ineroun classes\internship_project(Stores_sales_production)\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ineroun classes\internship_project(Stores_sales_production)\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 29, in predict_datapoint
    final_data = data.get_data_as_dataframe()
AttributeError: 'CustomData' object has no attribute 'get_data_as_dataframe'
[2024-09-15 19:40:57,960] 97 werkzeug -INFO - 127.0.0.1 - - [15/Sep/2024 19:40:57] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2024-09-15 19:41:00,531] 97 werkzeug -INFO - 127.0.0.1 - - [15/Sep/2024 19:41:00] "GET /predict HTTP/1.1" 200 -
[2024-09-15 19:41:26,250] 838 app -ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\ineroun classes\internship_project(Stores_sales_production)\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ineroun classes\internship_project(Stores_sales_production)\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ineroun classes\internship_project(Stores_sales_production)\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ineroun classes\internship_project(Stores_sales_production)\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 29, in predict_datapoint
    final_data = data.get_data_as_dataframe()
AttributeError: 'CustomData' object has no attribute 'get_data_as_dataframe'
[2024-09-15 19:41:26,251] 97 werkzeug -INFO - 127.0.0.1 - - [15/Sep/2024 19:41:26] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
